#include <iostream>
using namespace std;
int main()
{
	cout << "\t|_****************************************************************|\n"
		"\t|-----------------------------------------------------------------|\n"
		"\t|Name           | Rizelle B. Bautista                             |\n"
		"\t|---------------|-------------------------------------------------|\n"
		"\t|SHS Strand     | Science, Technology, Engineering and Mathematics|\n"
		"\t|---------------|-------------------------------------------------|\n"
		"\t|Motto          | \"The only way to do great work is to love what  |\n"
		"\t|               |you do.If you haven't found it yet, keep looking.|\n"
		"\t|               | Don't settle.\"                                  |\n"
		"\t|---------------|-------------------------------------------------|\n"
		"\t|What is your   | My biggest heartbreak was when my favorite uncle|\n"
		"\t|biggest        | died last year.                                 |\n"
		"\t|heartbreak?    |                                                 |\n"
		"\t|---------------|-------------------------------------------------|\n"
		"\t|Why chooses    | I have chosen T.I.P because I am a DOST scholar.|\n"
		"\t|T.I.P?         | I was supposed to go in P.U.P but my enrollment |\n"
		"\t|               | form hasn't been process and I've left with no  |\n"
		"\t|               | choice but to enroll in a school with level 3+  |\n"
		"\t|               | accreditation.                                  |\n"
		"\t|---------------|-------------------------------------------------|\n"
		"\t|Why choose CPE?| I chose Computer Engineering as my course       |\n"
		"\t|               | because I'm interested in technology and I want |\n"
		"\t|               | to build a business related to it.              |\n"
		"\t|---------------|-------------------------------------------------|\n"
		"\t|How do you feel| As a student with 0 background and knowledge    |\n"
		"\t|about          | in programming, I find it cool and amazing      |\n"
		"\t|programming    | whenever I learn something new. I really get    |\n"
		"\t|using C++?     | excited when my code works in first try.        |\n"
		"\t|               | I'm really thankful that even though at first,  |\n"
		"\t|               | I was disinterested in this course, I was able  |\n"
		"\t|               | catch up in our lessons and understand it well. |\n"
		"\t|               | Though, there are times that I get really       |\n"
		"\t|               | frustated whenever I get low score in my quiz.  |\n"
		"\t|               | I sometimes forget to include my learnings and  |\n"
		"\t|               | conclusion at the end of the activity. Thanks to|\n"
		"\t|               | the teachings of my professor, I was able to    |\n"
		"\t|               | follow the lessons well despite the fact that   |\n"
		"\t|               | it is my first time doing programming in C++.   |\n"
		"\t|               | My professor was able to clearly explain the    |\n"
		"\t|               | topics that made us to understand it easily and |\n"
		"\t|               | didn't find it difficult to learn and didn't get|\n"
		"\t|               | confused while learning it.                     |\n"
		"\t|               |                                                 |\n"
		"\t|               | In CPE 007, I was able to learn the basics of   |\n"
		"\t|               | programming in C++. I was also able to know the |\n"
		"\t|               | importance and use of it in real-life. I expect |\n"
		"\t|               | that in the future lessons, I'll be able to     |\n"
		"\t|               | create a program and a website that will be     |\n"
		"\t|               | useful to others as part of my learnings.       |\n"
		"\t|               | Additionally, I expect that in the next lessons,|\n"
		"\t|               | I will be able to improve my programming skills |\n"
		"\t|               | and widen my knowledge in this subject.         |\n"
		"\t-------------------------------------------------------------------\n";

		return 0;
	
}